#!/usr/bin/env node
var async = require('async');
var assert = require('assert');
var js = require('../lib/javascript');
var mongo = require('../lib/mongo');

mongo.initialize(function (error) 
{
  if (error) {
    console.log(js.pp(error));
    process.exit(-1);
  }
  else {
    var idCriterion;
    try {
      idCriterion = {_id:mongo.ObjectID(process.argv[2])};
    }
    catch (e) {
    }

    var nameCriterion = {name:process.argv[2]};
    if (idCriterion) {
      criterion = {$or: [ nameCriterion,
                          idCriterion ] };
    }
    else {
      criterion = nameCriterion;
    }
    console.log("Criterion: "+JSON.stringify(criterion,null,2));
    var description = process.argv.slice(3).join(" ");

    mongo.channels.findAndModify(criterion,
                                 {}, // sort
                                 {$set:{description:description}},
                                 {safe:true,multi:false,new:true},
                                 function (error, channel) {
                                   console.log("Result:"+JSON.stringify(error || channel,null,2));
                                   mongo.close();
                                   process.exit();
                                 });
  }
});
