#!/usr/bin/env node

var blacklist = require('../managers/blacklistManager');

var ids = process.argv.slice(2);
if ( ids.length == 0 ) {
  console.log( 'Blacklisting channels from to-blacklist file' );

  ids = require('fs').readFileSync([__dirname, 'to-blacklist'].join('/')).toString().split(/\s+/);

  var unique = { }
  for ( var i = 0; i < ids.length; i++ ) unique[ids[i]] = ids[i];

  ids = [ ];
  for ( var id in unique ) if (id) ids.push(id);
}

console.log( '\033[1mRemoving the following place channels from the blacklist:\033[0m' );
console.log( ids.join(', ') );
console.log( 'Please wait...' );

var done = function done ( error, result ) {
  if ( error ) {
    console.log( '\033[1;31mSomething went wrong: ' + error + '\033[0m' );
  }
  console.log( '\033[1mDone\033[0m' );
}

blacklist.removePlaces(ids, done);
