#!/usr/bin/env node

var blacklist = require('../managers/blacklistManager');
var mongo = require('../lib/mongo');
var description = require('../config').BLACKLIST;

//console.log( '\033[1mAdding to blacklist all described by:\033[0m' );
//console.log( JSON.stringify(description, null, 2) );
//console.log( 'Please wait...' );

var done = function done ( error, result ) {
  if ( error ) {
    console.log( 'Something went wrong: ' + error);
  }
  console.log( 'Done' );
}

mongo.initialize(function() { 
  blacklist.add(description, done);
});
