#!/usr/bin/env node

var js = require('../lib/javascript');
var mongo = require('../lib/mongo');
var userManager = require('../managers/userManager');
var argv = require('optimist')
  .usage("Set user's password\nUsage: $0 [--id user-id] [--password pass]")
  .demand(['id', 'password'])
  .argv;

mongo.initialize(function(error) { 
  if (error) { 
    console.log("db error: " + js.pp(error));
  }
  else {
    try {
      var id = mongo.ObjectID(argv.id);
      userManager.setUserPassword(id, argv.password, function(error) { 
        if (error) { 
          console.log("Failed: " + error.message);
        }
        else {
          console.log("OK");
        }
        mongo.close();
      });
    }
    catch (e) { 
      console.log("Invalid user-id: " + argv.id);
      mongo.close();
    }
  }
});

