#!/usr/bin/env node
var async = require('async');
var assert = require('assert');
var intercom = require('../lib/intercom');
var js = require('../lib/javascript');
var mongo = require('../lib/mongo');

var argv = require('optimist').usage('Register user accounts with intercom.\nUsage: $0 [--all] [--email user@domain]').argv;

mongo.initialize(function (error) 
{
  if (error) {
    console.log(js.pp(error));
    process.exit(-1);
  }
  else {
    if (argv.all) { 
      console.log("Initializing all accounts");
      intercom.initialize(done);
    }
    else if (argv.email) { 
      console.log("Initializing " + argv.email);
      intercom.initializeByEmail(argv.email, done);
    }
    else {
    }

    function done() {
      console.log("done.");
      mongo.close();
      process.exit();
    }
  }
});
