#!/bin/bash
scriptDir=$(cd `dirname $0` && pwd);
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Sets the default username and password for other blipboard scripts"
    echo "Usage: login.sh username password"
fi
echo "$1:$2" > $scriptDir/.user.login


