#!/usr/bin/python
import itertools
import fnmatch
import os
import subprocess

current_dir = os.path.dirname(__file__)
test_dir = os.path.normpath(os.path.join(current_dir,"../test"))
print test_dir
tests = []
for root, dirnames, filenames in os.walk(test_dir):
  for filename in fnmatch.filter(filenames, '*.test.js'):
      tests.append(os.path.join(root, filename));

for pair in itertools.combinations(tests,2):
    print "################################################################################"
    print "Executing mocha {0} {1}".format(pair[0],pair[1])
    print "################################################################################"

    if subprocess.call(["mocha",pair[0],pair[1]])!=0:
        quit()
