title Blipboard Pub/Sub Person

participant "Alice" as A
participant "Bob" as B
participant "Blipboard" as BB
participant "Darwin Cafe" as D
participant "Charlie" as C

A->BB: subscribe("Charlie")
B->BB: subscribe("Charlie")
note over C,BB
     Charlie publishes his message 
     while near Darwin Cafe
end note
C->BB: publish "Great espresso at Darwin Cafe"
note over A,BB: Alice is walking 2 blocks from Darwin Cafe. 
A->BB: update-location(lat,lng)
BB->A: notify("Great espresso at Darwin Cafe")
note over B,BB
     1 month of time elapses, 
     Bob is in South Park a few blocks from Darwin Cafe. 
end note
B->BB: update-location(lat,lng)
BB->B: notify("Great espresso at Darwin Cafe")
