blipDistributionService->mongo.blips:findOne
blipDistributionService->listenNetworkManager:findListeners
blipDistributionService->mongo.incomingBlips:find existing 
blipDistributionService->mongo.incomingBlips:update
blipDistributionService->mongo.incomingBlips:insert
